// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Newshore.Entity;

#nullable disable

namespace Newshore.Entity.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Newshore.Entities.DbContextEntities.FlightDto.FlightDto", b =>
                {
                    b.Property<int>("IdFlight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFlight"));

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTransport")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Transport")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFlight");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Newshore.Entities.DbContextEntities.JourneyDto.JourneyDto", b =>
                {
                    b.Property<int>("IdJourney")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJourney"));

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flights")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("IdJourney");

                    b.ToTable("Journey");
                });

            modelBuilder.Entity("Newshore.Entities.DbContextEntities.JourneyFlight.JourneyFlight", b =>
                {
                    b.Property<int>("IdJourneyFlight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJourneyFlight"));

                    b.Property<string>("FlightDto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdFlight")
                        .HasColumnType("int");

                    b.Property<int>("IdJourney")
                        .HasColumnType("int");

                    b.Property<string>("JourneyDto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdJourneyFlight");

                    b.ToTable("JourneyFlight");
                });

            modelBuilder.Entity("Newshore.Entities.DbContextEntities.TransportDto.TransportDto", b =>
                {
                    b.Property<int>("IdTransport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransport"));

                    b.Property<string>("FlightCarrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTransport");

                    b.ToTable("Transport");
                });
#pragma warning restore 612, 618
        }
    }
}
